project:
  type: website

website:
  title: "Alex Karp"
  navbar:
    left:
      - href: about.qmd
        text: About
      - index.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto